"use client";
import React, { useEffect } from 'react';
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import ScrollColorChange from "./components/ScrollColorChange";
import Script from "next/script";
import CanvasAnimation from "./components/CanvasAnimation";


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Function to handle the scroll event
  const handleScroll = () => {
    // Add your logic to update the canvas based on the scroll position here
    // For example, you can change the canvas background color based on the scroll position
    const scrollPosition = window.scrollY;

    // Example: Change canvas background color based on scroll position
    const canvas = document.getElementById('glcanvas');
    if (canvas) {
      if (scrollPosition > 200) {
        // Change background color when scroll position is greater than 200 pixels
        canvas.style.backgroundColor = ''; // Red background color
      } else {
        // Reset the background color
        canvas.style.backgroundColor = ''; // Default background color
      }
    }
  };

  // Attach the scroll event listener when the component mounts
  useEffect(() => {
    window.addEventListener('scroll', handleScroll);

    // Clean up the event listener when the component unmounts
    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);
  return (
    <html lang="en">
      <head>
        {/* <Script src="/js/cables-library.js"></Script> */}
        <Script src="/js/patch.js" />
      </head>
      <body className="inter.className text-white">
        <canvas
          className="fixed top-0 left-0 right-0 bottom-0 inset-0 z-0"
          id="glcanvas"
          width="100vw"
          height="100vh"
          tabIndex={1}
        ></canvas>

        <div className="relative z-20">
          {/* <ScrollColorChange> */}
            <Navbar />

            {children}
            <Footer />
          {/* </ScrollColorChange> */}
        </div>

        <script
          dangerouslySetInnerHTML={{
            __html: `
      function showError(errId, errMsg) {
        // handle critical errors here if needed
      }
      console.log("CABLES.jsLoaded");

      function patchInitialized(patch) {
        // You can now access the patch object (patch), register variable watchers and so on
      }

      function patchFinishedLoading(patch) {
        // The patch is ready now, all assets have been loaded
      }

      document.addEventListener("CABLES.jsLoaded", function (event) {
        CABLES.patch = new CABLES.Patch({
          patch: CABLES.exportedPatch,
          prefixAssetPath: "",
          assetPath: "assets/",
          jsPath: "js/",
          glCanvasId: "glcanvas",
          glCanvasResizeToWindow: true,
          onError: showError,
          onPatchLoaded: patchInitialized,
          onFinishedLoading: patchFinishedLoading,
          canvas: { alpha: true, premultipliedAlpha: true }
        });
      });

      // disable rubberband effect on mobile devices
      document.getElementById('glcanvas').addEventListener('touchmove', (e) => {
        e.preventDefault();
      }, false);
    `,
          }}
        ></script>
      </body>
    </html>
  );
}
