"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import React, { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [backgroundColor, setBackgroundColor] = useState("bg-white");

  // Function to handle scroll event
  const handleScroll = () => {
    const scrollY = window.scrollY;
    if (scrollY < 500) {
      setBackgroundColor("bg-white");
    } else if (scrollY < 1000) {
      setBackgroundColor("bg-red");
    } else if (scrollY < 1500) {
      setBackgroundColor("bg-gray");
    } else {
      setBackgroundColor("bg-black");
    }
  };

  useEffect(() => {
    // Add a scroll event listener when the component mounts
    window.addEventListener("scroll", handleScroll);

    return () => {
      // Remove the scroll event listener when the component unmounts
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  console.log(backgroundColor);

  return (
    <html lang="en">
      <body className={`${inter.className} ${backgroundColor}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
